--- 
version: "3"
services: 
  db: 
    build: 
      context: ./
      dockerfile: infiquestdb
    ports: 
      - "5432:5432"
  web: 
    build: 
      context: ./
      dockerfile: infiquestwebapp
    depends_on: 
      - db
    links:
      - db        
    ports: 
      - "9117:9117"

